sudo: false
language: bash

branches:
  only:
  - /^\d+\.\d+\.\d+(-\S*)?$/

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_script: "./.release/changelog > CHANGELOG.md"
script: bash ./.release/release.sh
