sudo: false
language: bash

addons:
  apt:
    packages:
    - luarocks
    - pandoc

before_script:
- luarocks install --local luacheck

script:
- $HOME/.luarocks/bin/luacheck .

before_deploy:
- lua .release/changelog > CHANGELOG.md
- curl -s https://raw.githubusercontent.com/Rainrider/packager/wowace/release.sh -o .release/release.sh

deploy:
  provider: script
  script: bash .release/release.sh
  skip_cleanup: true
  on:
    tags: true
    condition: '"$TRAVIS_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$'
