sudo: false
language: bash

branches:
  only:
  - /^\d+\.\d+\.\d+(-\S*)?$/

addons:
  apt:
    packages:
    - lua5.1
    - pandoc

before_script:
- lua .release/changelog > CHANGELOG.md
- curl -s https://raw.githubusercontent.com/Rainrider/packager/wowace/release.sh -o .release/release.sh

script:
- bash .release/release.sh
