name: Lint

# run on
on:
  push:
    branches:
    - master
    paths-ignore:
    - '.github/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Lint
      uses: nebularg/actions-luacheck@v1
      with:
        annotate: warning
        args: --no-color
