name: Package and Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Lua
      run: |
        echo '::group::apt update'
        sudo apt-get -qq update
        echo '::endgroup::'
        echo '::group::apt install lua 5.1'
        sudo apt-get install -qq lua5.1
        echo '::endgroup::'

    - name: Generate Changelog
      run: lua .release/changelog > CHANGELOG.md

    - name: Package and Release
      uses: BigWigsMods/packager@v1.0.3
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
